name: Clone Public Repo

on:
  repository_dispatch:
    types: [cloning_cocoa_spec_repo]

jobs:
  cloning_the_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty repository
        run: |
          echo "Finally echoing from github actions"

          git clone --depth 1 https://github.com/CocoaPods/Specs.git cocoapods
          echo "cloned repo"
          cd cocoapods
          echo "checked into cocoapods"
          pwd
          ls -al
          git remote remove origin
          echo "removed origin"
          rm -rf .git
          rm -rf .github
          echo "removed git and github"
          git init
          git config user.name "pradeepdodamani1445"
          git config user.email "pradeepdodamani1445@gmail.com"
          git remote set-url origin https://pradeepdodamani1445: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@github.com/pradeepdodamani1445/testrepo2.git
          echo "remote-set url has been set"
          git add .
          ehco "added git files"
          git commit -m "Commiting the Spec repo with depth 1"
          echo "commited files"
          curl -X POST -H "Authorization: token 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" -d '{
            "name": "testrepo2",
            "auto_init": false,
            "private": false
          }' "https://api.github.com/user/repos"
          echo "created repo"
          git push -f origin main
          echo "Pushed files to origin"
