name: Clone Public Repo

on:
  repository_dispatch:
    types: [cloning_cocoa_spec_repo]

jobs:
  cloning_the_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty repository
        run: |
          echo "Echoing from github actions" 
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{secrets.ACTIONS}}" \
            "https://api.github.com/repos/pradeepdodamani1445/testrepo3")  
          if [ $response -eq 200 ]; then
            echo "Repository exists."
            response2=$(curl -X DELETE -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{secrets.ACTIONS}}" \
            "https://api.github.com/repos/pradeepdodamani1445/testrepo3")
            if [ $response2 -eq 204 ]; then
              echo "Repository deleted successfully."
            elif [ $response2 -eq 404 ]; then
              echo "Github actions was not able to delete the repository please delete the repo manually in Github before proceeding to build in app center."
            fi
          fi
          git clone --depth 1 https://github.com/CocoaPods/Specs.git
          cd Specs
          curl -X POST -H "Authorization: token ${{secrets.ACTIONS}}" -d '{
          "name": "testrepo3",
          "auto_init": false,
          "private": false
          }' "https://api.github.com/user/repos"
          echo "created repo"
          git config user.name "pradeepdodamani1445"
          git config user.email "pradeepdodamani1445@gmail.com"
          echo "configured"
          git config --list
          git remote add own "https://github.com/pradeepdodamani1445/testrepo3.git"
          echo "added own"
          git remote set-url own https://${{secrets.ACTIONS}}@github.com/pradeepdodamani1445/testrepo3.git
          echo "set-url"
          git commit --amend --no-edit
          echo "amended"
          git push own master --force
          echo "Pushed files to origin"
