name: Clone Public Repo

on:
  repository_dispatch:
    types: [cloning_cocoa_spec_repo]

jobs:
  cloning_the_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty repository
        run: |
          echo "Echoing from github actions"
          git clone --depth 1 https://github.com/CocoaPods/Specs.git 
          cd Specs
          curl -X POST -H "Authorization: token ${{secrets.ACTIONS}}" -d '{
          "name": "testrepo3",
          "auto_init": false,
          "private": false
          }' "https://api.github.com/user/repos"
          echo "created repo"
          git config user.name "pradeepdodamani1445"
          git config user.email "pradeepdodamani1445@gmail.com"
          echo "configured"
          git config --list
          git remote add own "https://github.com/pradeepdodamani1445/testrepo3.git"
          echo "added own"
          git remote set-url own https://${{secrets.ACTIONS}}@github.com/pradeepdodamani1445/testrepo3.git
          echo "set-url"
          git commit --amend --no-edit
          echo "amended"
          git push own master --force
          echo "Pushed files to origin"
